### ISSUE TITLE
Importing comb from scipy.misc is deprecated

### ISSUE THREAD

**Issue by clarkenj** [lukassnoek/MVCA#1]
Hi, I would really like to try your code however comb has moved to scipy.special. Are you able to update this? Thank you!

**Comment by lukassnoek** [comment]
Hi, I don't see `comb` imported anywhere ... Where did you see this function imported/used?

**Comment by clarkenj** [comment]
This is the traceback I get:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-86aa9f46b582> in <module>
----> 1 from skbold.preproc import ConfoundRegressor

~/anaconda/lib/python3.7/site-packages/skbold/__init__.py in <module>
      8 from . import core
      9 from . import exp_model
---> 10 from . import postproc
     11 from . import feature_extraction
     12 from . import feature_selection

~/anaconda/lib/python3.7/site-packages/skbold/postproc/__init__.py in <module>
     38 
     39 from .extract_roi_info import extract_roi_info
---> 40 from .mvp_results import MvpResults, MvpAverageResults
     41 from .cluster_size_threshold import cluster_size_threshold
     42 

~/anaconda/lib/python3.7/site-packages/skbold/postproc/mvp_results.py in <module>
     10 from scipy import stats
     11 from itertools import combinations
---> 12 from scipy.misc import comb
     13 from copy import copy
     14 from sklearn.metrics import (accuracy_score, precision_score, recall_score,

ImportError: cannot import name 'comb' from 'scipy.misc' (/Users/natashaclarke/anaconda/lib/python3.7/site-packages/scipy/misc/__init__.py)

**Comment by lukassnoek** [comment]
Ah, I updated the `skbold` package now. You need to reinstall it from source though (i.e., not using `pip install skbold`).

**Comment by clarkenj** [comment]
Awesome, thank you!
